name: vca
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - snakemake-minimal=7.20
  - bwa=0.7.17
  - samtools=1.15
  - bcftools=1.15
  - bedtools=2.30
  - htslib=1.15
  - pysam
  - pandas
  - numpy
  - pip
  - pip:
    - matplotlib
