name: vca
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - snakemake=9.15
  - bwa=0.7.19
  - samtools=1.21
  - bcftools=1.21
  - bedtools=2.31.1
  - htslib=1.21
  - gatk=3.8
  - pysam
  - pandas
  - numpy
  - pip
  - pip:
    - matplotlib
